### ISSUE TITLE
api not working

### ISSUE THREAD

**Issue by abhijitpa1992** [HellaVentures/Car-Diagnostic-API#3]
We have already registered with Bluemix service of IBM and we have been using this service of ibm bluemix catalog since last 6 months. Our Bluemix account has more than  1000 USD credit, but still we are getting this response since yesterday

<404 Not Found: Requested route ('a3b84f99-5529-45b3-be60-225668286daf.eu-gb.mybluemix.net') does not exist.>

CLIENT_ID = "xxx”
CLIENT_SECRET = "xxx"

**Comment by ericmorfamorales** [comment]
I've fixed an issue related to API connect on the Bluemix platform. Can you please check if the API works again for you?

**Comment by Birnhackster** [comment]
Say, is there some action there?  Many calls?

**Comment by abhijitpa1992** [comment]
The api call is working fine now. Thanks for the support.
Was the issue from our side?
Also on how to avoid these kind of issues?

**Comment by ericmorfamorales** [comment]
This was a problem from our side. If something similar happens in the future, just post an issue in this repo and we will help you asap.

Also, please don't post your client_id and cliend_secret in an issue description. This way you allow other people to use your API account. I've deleted the initial problem description so that this cannot happen.

**Comment by abhijitpa1992** [comment]
Great. Thanks man. Can I have your skype to have a faster response time between us....

**Comment by ncr9108** [comment]
Any Solution For This?

404 Not Found: Requested route ('a3b84f99-5529-45b3-be60-225668286daf.eu-gb.mybluemix.net') does not exist.
